spring:
  application:
    name: @project.artifactId@
  data:
    web:
      pageable:
        serialization-mode: via_dto
  jpa:
    hibernate:
      # schema is managed by Flyway, only validate
      ddl-auto: validate
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration/schema
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:user, repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

server:
  error:
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  build:
    java.version: @java.version@
    spring-cloud.version: @spring-cloud-dependencies.version@

security:
  userInfoUri: https://api.github.com/user
  loggingMode: CHANGING
  loggingIgnoreList: # Optional
    - "/health"
    - "/metrics"