spring:
  application:
    name: gitwrapped-backend
  data:
    web:
      pageable:
        serialization-mode: via_dto
  jpa:
    hibernate:
      # schema is managed by Flyway, only validate
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration/schema

server:
  error:
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  application:
    name: gitwrapped-backend
    version: 0.0.1-SNAPSHOT
    description: This is an Annual Review app for Git Users
  build:
    java.version: 21.0.5
    spring-cloud.version: 2024.0.1